"""Profile management - re-exports from SDK."""

# Re-export everything from SDK profiles
from gwsa.sdk.profiles import (
    ADC_PROFILE_NAME,
    PROFILE_NAME_PATTERN,
    ADC_FILE_PATH,
    get_profiles_dir,
    is_valid_profile_name,
    get_profile_dir,
    get_profile_token_path,
    get_profile_metadata_path,
    list_profiles,
    get_active_profile_name,
    get_active_profile,
    set_active_profile,
    profile_exists,
    get_profile_status,
    load_profile_metadata,
    save_profile_metadata,
    create_profile,
    delete_profile,
    update_profile_metadata,
    get_adc_metadata_path,
    load_adc_cached_metadata,
    update_adc_cached_metadata,
    check_adc_changed,
    get_adc_cached_email,
    get_adc_cached_scopes,
    get_adc_quota_project,
)

__all__ = [
    "ADC_PROFILE_NAME",
    "PROFILE_NAME_PATTERN",
    "ADC_FILE_PATH",
    "get_profiles_dir",
    "is_valid_profile_name",
    "get_profile_dir",
    "get_profile_token_path",
    "get_profile_metadata_path",
    "list_profiles",
    "get_active_profile_name",
    "get_active_profile",
    "set_active_profile",
    "profile_exists",
    "get_profile_status",
    "load_profile_metadata",
    "save_profile_metadata",
    "create_profile",
    "delete_profile",
    "update_profile_metadata",
    "get_adc_metadata_path",
    "load_adc_cached_metadata",
    "update_adc_cached_metadata",
    "check_adc_changed",
    "get_adc_cached_email",
    "get_adc_cached_scopes",
    "get_adc_quota_project",
]
